<?php


 /**
  * Documentos Value Object.
  * This class is value object representing database table documentos
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */




class Documentos {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    var $idDocumento;
    var $titulo;
    var $descripcion;
    var $tipo;
    var $ruta;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    function Documentos () {

    }

    /* function Documentos ($idDocumentoIn) {

          $this->idDocumento = $idDocumentoIn;

    } */


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    function getIdDocumento() {
          return $this->idDocumento;
    }
    function setIdDocumento($idDocumentoIn) {
          $this->idDocumento = $idDocumentoIn;
    }

    function getTitulo() {
          return $this->titulo;
    }
    function setTitulo($tituloIn) {
          $this->titulo = $tituloIn;
    }

    function getDescripcion() {
          return $this->descripcion;
    }
    function setDescripcion($descripcionIn) {
          $this->descripcion = $descripcionIn;
    }

    function getTipo() {
          return $this->tipo;
    }
    function setTipo($tipoIn) {
          $this->tipo = $tipoIn;
    }

    function getRuta() {
          return $this->ruta;
    }
    function setRuta($rutaIn) {
          $this->ruta = $rutaIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    function setAll($idDocumentoIn,
          $tituloIn,
          $descripcionIn,
          $tipoIn,
          $rutaIn) {
          $this->idDocumento = $idDocumentoIn;
          $this->titulo = $tituloIn;
          $this->descripcion = $descripcionIn;
          $this->tipo = $tipoIn;
          $this->ruta = $rutaIn;
    }


    /** 
     * hasEqualMapping-method will compare two Documentos instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    function hasEqualMapping($valueObject) {

          if ($valueObject->getIdDocumento() != $this->idDocumento) {
                    return(false);
          }
          if ($valueObject->getTitulo() != $this->titulo) {
                    return(false);
          }
          if ($valueObject->getDescripcion() != $this->descripcion) {
                    return(false);
          }
          if ($valueObject->getTipo() != $this->tipo) {
                    return(false);
          }
          if ($valueObject->getRuta() != $this->ruta) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    function toString() {
        $out = $this->getDaogenVersion();
        $out = $out."\nclass Documentos, mapping to table documentos\n";
        $out = $out."Persistent attributes: \n"; 
        $out = $out."idDocumento = ".$this->idDocumento."\n"; 
        $out = $out."titulo = ".$this->titulo."\n"; 
        $out = $out."descripcion = ".$this->descripcion."\n"; 
        $out = $out."tipo = ".$this->tipo."\n"; 
        $out = $out."ruta = ".$this->ruta."\n"; 
        return $out;
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
/*    function clone() {
        $cloned = new Documentos();

        $cloned->setIdDocumento($this->idDocumento); 
        $cloned->setTitulo($this->titulo); 
        $cloned->setDescripcion($this->descripcion); 
        $cloned->setTipo($this->tipo); 
        $cloned->setRuta($this->ruta); 

        return $cloned;
    }*/



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    function getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

?>