<?php
	$dbhost="localhost";
	$dbName="cideacauca";
	$dbUser="root";
	$dbPassword="";
	$docLocation="../uploads/documentos";
	$bannerLocation="../uploads/banner";
	$experienciasLocation="../uploads/experiencias";
?>